"""
content/lectures.py
CSE Life: Compile & Conquer
Created by: Ayesha Saheba Mostafa (dev4-aysha-narrative)

Lecture scripts — one entry per course code. Pure data, no engine
or pygame imports. get_lecture() never raises and never returns None.
"""
from __future__ import annotations

LECTURE_SCRIPTS: dict[str, dict] = {
    # ── BATCH 1 ─────────────────────────────────────────────
    "CSE1102": {
        "title": "Introduction to Programming",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "programming_language",
        "lines": [
            "Today, we peel back the curtain what happens inside the machine when your code runs.",
            "The CPU is the part that actually executes every instruction; RAM just holds things for it.",
            "Modulo gives the leftover, not the quotient like dividing cookies and counting what's left over.",
            "An algorithm that runs in constant time takes the same number of steps no matter the input size.",
            "Don't fear the machine underneath, understanding it makes every bug easier to find.",
        ],
    },
    "GEF1101": {
        "title": "Academic English I",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "technical_communication",
        "lines": [
            "Let's talk about the sentence not just what it says, but how it's built.",
            "An adverb modifies a verb, an adjective, or another adverb it answers how, when, or where.",
            "Passive voice flips the actor and the acted-upon: 'the researcher conducted it' becomes 'it was conducted.'",
            "A strong thesis is a claim you could argue against, not just a topic you're describing.",
            "Good writing isn't about big words. It's about a sentence that says exactly what you mean.",
        ],
    },
    "MAT1101": {
        "title": "Differential and Integral Calculus",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Calculus asks one question over and over: how fast is this changing, right now?",
            "The power rule isn't magic. Derive it once from first principles and you'll never need to memorize it.",
            "Integration reverses differentiation give it a rate, it hands you back the total.",
            "When a limit gives you zero over zero, don't panic and don't guess there's a rule for exactly that case.",
            "Mathematics rewards the student who asks why, not the one who only asks how.",
        ],
    },
    "PHY1101": {
        "title": "Physics I",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Force has a name and a unit - Newton and it is not the same thing as mass or weight.",
            "Work is force times distance, in the direction of motion push a wall all day and you've done none.",
            "Momentum is always conserved in a collision. Kinetic energy only survives if the collision is elastic.",
            "Physics doesn't reward memorized formulas. It rewards knowing which one actually applies.",
        ],
    },
    "PHY1102": {
        "title": "Physics I Lab",
        "lecturer": "professor_hoque",
        "emotion": "strict",
        "skill_id": "general",
        "lines": [
            "A lab is not about getting the 'right' number - it's about knowing how sure you are of it.",
            "For thickness finer than a ruler can read, we reach for the screw gauge, not a better eye.",
            "Friction and air resistance push your result the same way every trial that's systematic error, not noise.",
            "Plot voltage against current for a resistor the slope of that straight line is the resistance itself.",
            "Take three readings, not one. A single reading is a guess wearing a lab coat, nothing more.",
        ],
    },
    "CSE1201": {
        "title": "Structured Programming",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "programming_language",
        "lines": [
            "Let's look at how C stores the small stuff the building blocks before the big programs.",
            "A char holds a single character, one byte, nothing more that's what makes it lean and fast.",
            "sizeof tells you how much memory a type occupies on most systems, an int takes four bytes.",
            "Mark a local variable static, and it remembers its value between calls instead of resetting each time.",
            "Don't worry if this feels like a lot every strong C programmer built it up one keyword at a time.",
        ],
    },
    "CSE1202": {
        "title": "Structured Programming Lab",
        "lecturer": "professor_rahman",
        "emotion": "approving",
        "skill_id": "programming_language",
        "lines": [
            "Today's lab is about talking to the outside world reading input and reading files.",
            "scanf reads formatted input from the keyboard - get the format specifier wrong, and it reads garbage.",
            "Open a missing file in read mode and fopen won't crash it quietly returns NULL. Always check for it.",
            "An array name decays into a pointer arr plus three steps forward three whole elements, not three bytes.",
            "Good work pushing through the pointer confusion today that's the hardest wall in this course.",
        ],
    },
    "CSE1203": {
        "title": "Discrete Mathematics",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Logic and structure today we build the vocabulary the rest of your degree depends on.",
            "AND is strict: the result is true only when every single input is true. One false ruins it.",
            "In a complete graph, every vertex connects to every other vertex count the pairs and you have your edges.",
            "A relation that's reflexive, symmetric, and transitive all at once earns a name: equivalence relation.",
            "Don't memorize these definitions. Test them against an example until you'd catch a wrong one.",
        ],
    },
    "GEF2101": {
    "title": "Academic English 3",
    "lecturer": "professor_rahman",
    "emotion": "neutral",
    "skill_id": "general",
    "lines": [
        "Academic integrity begins with acknowledging every source and idea that isn't original to you.",
        "Citing your sources properly is the single most essential step to avoiding accidental plagiarism.",
        "Choose your transition words intentionally—'however' signals contrast, while 'therefore' marks a conclusion.",
        "Formal academic writing demands precision; avoid informal phrasing like 'a lot' or 'a big deal'.",
        "Clear, honest writing reflects clear, honest research. Treat your citations with care.",
    ],
},
    "MAT1201": {
        "title": "Coordinate Geometry and Linear Algebra",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "A matrix isn't a grid to memorize it's a transformation waiting to happen.",
            "For a two by two matrix, the determinant is one diagonal product minus the other know why, not just how.",
            "Distance between two points isn't guesswork it falls straight out of the Pythagorean theorem.",
            "A matrix is invertible only when its determinant isn't zero. Zero determinant means there's no inverse.",
            "Compute the determinant before you attempt the inverse. Skipping that step wastes your own time.",
        ],
    },
    "ESK1110": {
        "title": "Study Skills",
        "lecturer": "professor_rahman",
        "emotion": "approving",
        "skill_id": "general",
        "lines": [
            "Studying and rereading your notes are not the same activity, even though they feel similar.",
            "The Cornell method splits your page into cues and notes, with a summary waiting at the bottom.",
            "A SMART goal has to be specific - 'study more' isn't a goal, it's a wish with good intentions.",
            "SQ3R walks you through five steps: survey, question, read, recite, and review in that order.",
            "Small, spaced sessions beat one long night every time. Trust the method, not the panic.",
        ],
    },
    "PHY1301": {
        "title": "Physics II",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Electricity and magnetism follow their own laws, and today we start connecting them.",
            "Coulomb's law isn't linear with distance double the distance and the force drops far more than half.",
            "Gauss's law for magnetism has a quiet but firm implication: no one has ever found an isolated magnetic pole.",
            "The photoelectric effect is where light stops acting only like a wave and starts acting like a particle.",
            "Every formula you learn this term rests on an experiment someone verified first. Respect that.",
        ],
    },

    # ── BATCH 2 ─────────────────────────────────────────────
    "CSE1301": {
        "title": "Data Structures",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "dsa",
        "lines": [
            "Every data structure exists to answer one question: how do you want to get your data back out?",
            "A stack only lets you touch the top last one in is always the first one out.",
            "Binary search halves the space to check with every comparison that's why it beats scanning one by one.",
            "A tree node can branch, but a binary tree draws a hard line: at most two children, never more.",
            "If trees and stacks feel abstract, draw them out. Your hand understands structure faster than your eyes.",
        ],
    },
    "CSE1302": {
        "title": "Data Structures Lab",
        "lecturer": "professor_rahman",
        "emotion": "approving",
        "skill_id": "dsa",
        "lines": [
            "Implementing a stack in an array means tracking one thing carefully - where the top actually is.",
            "An empty stack isn't a zero by convention, we mark it with an index that couldn't be a real position.",
            "Dequeue is the queue's exit door it always removes from the front, never the back.",
            "A circular linked list has no true end the last node's next pointer loops back into the list itself.",
            "You're building real pointer intuition now that discomfort earlier this semester was doing its job.",
        ],
    },
    "EEE1101": {
        "title": "Electrical Circuit 1",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "A circuit obeys its laws whether or not you've memorized them today we make sure you have.",
            "Ohm's law ties voltage, current, and resistance together know the relationship, not just the letters.",
            "Kirchhoff's Current Law says every bit of current entering a node has to leave it nothing piles up there.",
            "Resistors in parallel don't just add the combined value always lands below the smallest single resistor.",
            "Formulas are shortcuts for people who already understand the circuit. Understand it first.",
        ],
    },
    "EEE1102": {
        "title": "Electrical Circuit 1 Lab",
        "lecturer": "professor_hoque",
        "emotion": "strict",
        "skill_id": "general",
        "lines": [
            "A meter placed wrong doesn't just give a bad reading it can change the very circuit you're measuring.",
            "An ammeter goes in series, in the path of the current itself, never bridging across a component.",
            "A voltmeter with too little internal resistance loads the circuit down and quietly lies about the voltage.",
            "To find Thevenin resistance, kill every source first short the voltage ones, open the current ones.",
            "Respect the instrument. It reports exactly what you connected, not what you intended.",
        ],
    },
    "UCC1201": {
        "title": "History of the Emergence of Independent Bangladesh",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "History isn't a list of dates to memorize it's a chain of decisions people made under pressure.",
            "1952 wasn't just a protest. Students died defending the right to speak their own language.",
            "On the seventh of March, 1971, one speech at Race Course Maidan set the direction for everything after.",
            "A government doesn't need a capital to exist the provisional government of 1971 led from exile.",
            "Every date in this course belongs to real people who chose to act. Try to remember it that way.",
        ],
    },
    "ESK1111": {
        "title": "Healthy Life Skills",
        "lecturer": "professor_rahman",
        "emotion": "approving",
        "skill_id": "general",
        "lines": [
            "Health isn't just the body this course treats sleep, emotion, and self-awareness as skills too.",
            "Adults need seven to nine hours of sleep, consistently, not just on the nights you can afford it.",
            "Emotional intelligence starts with noticing your own state before you try to read anyone else's.",
            "BMI is a simple ratio of weight to height useful as a rough signal, not a verdict on your worth.",
            "Taking care of yourself isn't indulgent. It's the foundation everything else in your semester stands on.",
        ],
    },
    "MAT2101": {
        "title": "Differential Equations and Numerical Analysis",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Today we bridge two things exact equations and the approximate methods we lean on when exact ones fail.",
            "In a differential equation, degree and order are not the same thing - confusing them costs you the problem.",
            "A sign change between two points means the function crosses zero somewhere between them. That's bisection.",
            "Newton-Raphson converges fast each correct digit roughly doubles the next, once you're close to the root.",
            "A method that doesn't converge is worse than useless. Check for convergence before you trust any answer.",
        ],
    },
    "GEF1201": {
        "title": "English II",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "technical_communication",
        "lines": [
            "Let's move past the sentence and into how sentences connect to each other.",
            "A compound sentence joins two complete thoughts - get the comma and conjunction wrong, and the seams show.",
            "Words like however and furthermore don't just transition they tell the reader how to weigh what follows.",
            "Tone isn't what a story says, it's the attitude behind how the author says it.",
            "Reading with attention to tone will change how you read everything, not just what's assigned.",
        ],
    },
    "CSE2101": {
        "title": "Digital Logic Design",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Every circuit you'll ever design reduces to combinations of a handful of logic gates.",
            "AND is unforgiving - output is true only when every input agrees. One zero and the whole thing fails.",
            "Boolean algebra isn't decoration - simplify the expression correctly and you simplify the actual hardware.",
            "A multiplexer's select lines decide which input reaches the output more inputs demand more select lines.",
            "Truth tables don't lie. When your circuit disagrees with one, trust the table, not your gate diagram.",
        ],
    },
    "CSE2102": {
        "title": "Digital Logic Design Lab",
        "lecturer": "professor_hoque",
        "emotion": "strict",
        "skill_id": "general",
        "lines": [
            "Today we move from theory to the chips themselves the same logic, now with pins and voltage.",
            "The 7400 series names its ICs by function learn the family, and the datasheet stops being a mystery.",
            "An inverter does exactly one job: whatever comes in high goes out low, and low comes out high.",
            "A JK flip-flop has a special case feed both inputs high, and instead of set or reset, it toggles.",
            "Check your wiring against the diagram twice before you power it on. Smoke is not a debugging tool.",
        ],
    },
    "CSE2103": {
        "title": "Object Oriented Programming",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "oop",
        "lines": [
            "Object-oriented programming is a different way of organizing thought, not just a different syntax.",
            "Inheritance lets a child class pick up its parent's properties and behavior without rewriting them.",
            "Overloading means several methods share a name but not a signature the parameters tell them apart.",
            "An abstract class can hold real logic, but you can never create an object directly from it.",
            "These ideas click faster with practice than with definitions. Write a small class and watch it happen.",
        ],
    },
    "CSE2104": {
        "title": "Object Oriented Programming Lab",
        "lecturer": "professor_rahman",
        "emotion": "approving",
        "skill_id": "oop",
        "lines": [
            "Today we put objects on the heap and start controlling exactly when they live and die.",
            "The new keyword hands you a fresh object on the heap and the responsibility to manage its lifetime.",
            "Marking a member private isn't paranoia it's a promise that only the class itself can touch it.",
            "A virtual destructor makes sure deleting a derived object through a base pointer cleans up every layer.",
            "You handled memory ownership well today that instinct is what separates a script from real software.",
        ],
    },
    "ESK1112": {
        "title": "Social Skills",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Today isn't about manners it's about how a room of people actually functions together.",
            "Active listening means following, responding, and remembering - not just waiting for your turn to talk.",
            "Assertive communication respects your rights and the other person's at the same time. Neither gets sacrificed.",
            "A group can quietly agree on a bad idea just to avoid conflict that failure has a name worth knowing.",
            "The strongest people in a room are rarely the loudest ones. Watch how they actually listen.",
        ],
    },

    # ── BATCH 3 ─────────────────────────────────────────────
    "CSE2201": {
        "title": "Algorithms",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "dsa",
        "lines": [
            "An algorithm isn't just correct or incorrect - it's fast or slow, and that difference matters at scale.",
            "Merge sort doesn't sort the array at once it splits the problem down until it's trivial, then combines.",
            "Quick sort's average performance is excellent, but average isn't guaranteed. Know what breaks it.",
            "Dijkstra's algorithm only promises the shortest path when no edge weight is allowed to be negative.",
            "Don't just learn what an algorithm does. Learn the one assumption that makes it work at all.",
        ],
    },
    "CSE2202": {
        "title": "Algorithms Lab",
        "lecturer": "professor_hoque",
        "emotion": "strict",
        "skill_id": "dsa",
        "lines": [
            "Breadth-first search explores level by level, and the structure that enforces that order is a queue.",
            "Memoization isn't a new algorithm it's a discipline: never compute the same subproblem twice.",
            "Detecting a cycle while building a minimum spanning tree needs a structure built exactly for that question.",
            "An algorithm that's correct on paper and wrong in code taught you nothing except how to type.",
            "Trace it by hand before you trust the output. The debugger shows you what happened, not why.",
        ],
    },
    "CSE2203": {
        "title": "Computer Organization and Architecture",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Underneath every line of code you write, there's a machine doing arithmetic and moving bits around.",
            "The ALU does the actual computing. Everything else in the CPU exists to feed it and store its results.",
            "One register always points to the next instruction, never the current one being decoded right now.",
            "Pipelining speeds things up until one instruction needs a result the previous one hasn't produced yet.",
            "Architecture isn't abstract once you've traced one instruction through the whole cycle by hand.",
        ],
    },
    "STA2101": {
        "title": "Statistics and Probability",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Statistics turns a pile of numbers into a claim you can actually defend or challenge.",
            "The mean is sensitive to every value in the set one extreme number can drag it far from the center.",
            "When two events are truly independent, their joint probability is just the product of each one alone.",
            "A normal distribution's curve always encloses the same total area, no matter how it's stretched or shifted.",
            "A statistic without context is just a number. Always ask what it's actually measuring.",
        ],
    },
    "EEE1301": {
        "title": "Electronic Device and Circuits 1",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Semiconductors aren't conductors or insulators they're something we can deliberately tune in between.",
            "Doping silicon with the right impurity decides whether current flows by extra electrons or by missing ones.",
            "A silicon diode doesn't just switch on at zero volts it needs a real barrier potential overcome first.",
            "A transistor in active region has one junction forward biased and the other reverse biased, not both alike.",
            "Every device here behaves predictably once you stop guessing and start reading its actual bias condition.",
        ],
    },
    "EEE1302": {
        "title": "Electronic Device and Circuits 1 Lab",
        "lecturer": "professor_hoque",
        "emotion": "strict",
        "skill_id": "general",
        "lines": [
            "A diode's entire personality is captured in one behavior: current flows one way, and refuses the other.",
            "A bridge rectifier doesn't waste half the input wave it uses four diodes so both halves get used.",
            "A rectified wave still ripples until a capacitor smooths it placed right across the output, not before it.",
            "Watch the diode's orientation before you power the board. Reversed, it won't rectify anything.",
            "A clean waveform on the scope is proof, not decoration. Don't skip capturing it.",
        ],
    },
    "CSE2200": {
        "title": "Design Project-I",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "This course isn't about learning new theory it's about proving you can build something with what you know.",
            "A working prototype matters more right now than a polished one. Get something running end to end first.",
            "Track changes with version control from day one - losing work to a bad overwrite is an avoidable disaster.",
            "MVC separates your data, your interface, and the logic connecting them. Mixing those layers costs you later.",
            "Don't wait for the idea to feel perfect. Projects improve by being built, not by being planned forever.",
        ],
    },
    "ESK1113": {
        "title": "Professional Skills",
        "lecturer": "professor_rahman",
        "emotion": "approving",
        "skill_id": "general",
        "lines": [
            "The skills that get you hired aren't always the technical ones - today we work on the other half.",
            "A resume isn't your life story. It's a targeted argument for why you fit this specific role.",
            "Answering a behavioral question well means walking through the situation, your action, and the actual result.",
            "A professional email earns its reply with a clear subject line and a respectful, direct tone.",
            "Confidence in an interview isn't arrogance. It's just being prepared enough not to perform.",
        ],
    },
    "CSE2301": {
        "title": "Database Management System",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "databases_sql",
        "lines": [
            "A database isn't just storage it's a set of promises about how your data stays consistent.",
            "SQL is the language you speak to a database, and most conversations start by asking it to select something.",
            "A primary key's whole job is uniqueness no two rows can ever share one, by definition.",
            "ACID isn't jargon to memorize blindly each letter protects your data from a specific kind of disaster.",
            "Design your tables carefully before you touch a single query. Bad structure punishes every query after.",
        ],
    },
    "CSE2302": {
        "title": "Database Management System Lab",
        "lecturer": "professor_rahman",
        "emotion": "approving",
        "skill_id": "databases_sql",
        "lines": [
            "Today we go from describing what data you want to actually pulling it out of a real table.",
            "HAVING isn't WHERE's twin it filters groups after aggregation, once the grouping has already happened.",
            "A join decides how much of each table survives left, right, and full each keep a different set of rows.",
            "Write the query on paper first if you're stuck. The logic rarely fails; the syntax just gets in the way.",
            "You're starting to think in sets now instead of loops that shift is exactly what this course is for.",
        ],
    },
    "CSE2303": {
        "title": "Automata and Theory of Computation",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "This course asks a strange question: what can a computer compute at all, before we even discuss speed?",
            "A finite automaton recognizes patterns with no memory of what came before beyond its current state.",
            "Give that automaton a stack to remember with, and it can suddenly handle a much richer class of languages.",
            "The Turing machine isn't a real device you'll build it's the ceiling of what any algorithm can ever do.",
            "Don't rush this material. Every other theory course you take assumes you actually understood this one.",
        ],
    },
    "CSE2305": {
        "title": "Operating Systems",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "An operating system's real job is arbitration deciding who gets the CPU, memory, and disk, and when.",
            "A process is a program in motion, mid-execution, with its own state. The program on disk is just potential.",
            "Shortest Job First minimizes average waiting time, but it demands something you rarely know in advance.",
            "Deadlock needs four conditions holding at once remove any single one, and the deadlock can't form.",
            "Every OS concept here exists to solve one problem: many things want the same limited resource.",
        ],
    },
    "CSE2306": {
        "title": "Operating Systems Lab",
        "lecturer": "professor_hoque",
        "emotion": "strict",
        "skill_id": "general",
        "lines": [
            "Creating a new process in Unix doesn't start from nothing it clones the process that's already running.",
            "A parent process that doesn't wait for its child risks losing track of it entirely once it terminates.",
            "The producer-consumer problem breaks the moment two processes touch shared memory without synchronization.",
            "A semaphore isn't magic it's a counter with discipline, and the discipline is what prevents the race.",
            "Race conditions don't announce themselves. They fail rarely, randomly, and always at the worst time.",
        ],
    },
    "GED2159": {
        "title": "Professional Ethics",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Ethics in engineering isn't abstract philosophy it's the decision you make when nobody's checking.",
            "Reporting unsafe or illegal practice within your own organization is a specific act with a specific name.",
            "A patent doesn't protect an idea forever - it grants exclusive rights for a limited, defined period.",
            "Every major code of ethics in computing puts one thing above deadlines and profit: public safety.",
            "The hardest ethical calls rarely look dramatic. They look like a quiet email you almost don't send.",
        ],
    },

    # ── BATCH 4 ─────────────────────────────────────────────
    "CSE3101": {
        "title": "Microprocessor and Microcontroller",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "A microprocessor's address bus width isn't trivial it directly caps how much memory it can ever reach.",
            "More address lines mean more reachable memory, a relationship you should be able to derive, not just recall.",
            "RISC and CISC made opposite bets one keeps instructions simple and fast, the other packs in complexity.",
            "Neither architecture is universally right. Each trades simplicity against flexibility differently.",
            "Know which processor family you're reading about before you trust an instruction set's behavior.",
        ],
    },
    "CSE3102": {
        "title": "Microprocessor and Microcontroller Lab",
        "lecturer": "professor_hoque",
        "emotion": "strict",
        "skill_id": "general",
        "lines": [
            "Assembly forces you to think the way the processor actually thinks one register, one instruction at a time.",
            "MOV doesn't calculate anything. It just places a value where you tell it, nothing more, nothing less.",
            "Serial communication on these boards runs through two dedicated lines one to transmit, one to receive.",
            "An interrupt service routine isn't optional cleanup code. It's the handler for something happening right now.",
            "Read the datasheet before you wire the board. Guessing pin behavior burns boards, not just time.",
        ],
    },
    "GED_ELEC3": {
        "title": "GED Elective 3",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Social science doesn't run experiments in a lab - it studies people through surveys and real observation.",
            "When demand for something rises and supply can't keep up, price doesn't stay still. It responds.",
            "Globalization ties economies and cultures together tighter than any single nation controls on its own.",
            "This elective trains a different muscle than your core courses - reading people and systems, not just code.",
        ],
    },
    "CSE3103": {
        "title": "System Analysis and Design",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Before anyone writes code, someone has to decide exactly what the system is supposed to do and why.",
            "A data flow diagram doesn't show your code's structure it shows how information actually moves through it.",
            "Functional requirements describe what a system does. Non-functional ones describe how well it does it.",
            "Confusing those two categories is the single most common mistake in early-stage project planning.",
            "Good analysis up front saves you from redesigning everything three weeks before the deadline.",
        ],
    },
    "GED2243": {
        "title": "Environment and Sustainability",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Sustainability isn't about stopping progress it's about not spending the future to pay for today.",
            "Carbon dioxide gets most of the attention because of how directly it drives human-caused warming.",
            "Meeting today's needs without compromising tomorrow's is the actual definition worth remembering here.",
            "Electronic waste isn't just clutter it carries heavy metals that don't belong loose in soil or water.",
            "Every technology you'll build in this degree eventually becomes someone's disposal problem. Plan for that.",
        ],
    },
    "CSE3120": {
        "title": "Web Programming",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "web_app_dev",
        "lines": [
            "HTML doesn't style anything and doesn't behave dynamically its only job is structure and content.",
            "Reaching into the page to change an element's content by its ID is one of the most common things you'll write.",
            "A page that reloads for every action feels ancient. Asynchronous requests let it update without a refresh.",
            "Fetching data in the background is what makes an app feel alive instead of like a stack of static pages.",
            "Every modern web app you admire is built from these same small pieces, just composed with more care.",
        ],
    },
    "CSE3201": {
        "title": "Artificial Intelligence & Machine Learning",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "ai_tools",
        "lines": [
            "A search algorithm with a good heuristic doesn't wander - it has a sense of which direction is promising.",
            "Supervised learning needs answers already attached to its examples. It learns by comparing guess to truth.",
            "A model that memorizes its training data instead of the underlying pattern will fail the moment data is new.",
            "That failure has a name, and recognizing it early saves you from trusting a model that only looks accurate.",
            "The math behind these models matters less at first than knowing exactly what problem you're pointing them at.",
        ],
    },
    "CSE3202": {
        "title": "Artificial Intelligence & Machine Learning Lab",
        "lecturer": "professor_rahman",
        "emotion": "approving",
        "skill_id": "ai_tools",
        "lines": [
            "Before you build a model, you need arrays that behave, and that's exactly what NumPy is built for.",
            "Training a model in this lab always follows the same shape - you fit it to data before you ask it to predict.",
            "Plain accuracy lies to you on imbalanced data. A model can score high just by guessing the common class.",
            "That's why precision, recall, and the balance between them matter more than one comfortable number.",
            "You're starting to question your own results instead of just trusting the score that's real progress.",
        ],
    },
    "CSE3203": {
        "title": "Software Engineering",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "debugging_testing",
        "lines": [
            "Software engineering is what separates a working program from a system a team can actually maintain.",
            "Waterfall moves in one direction, phase by phase. Skip validating early, and you find out very late.",
            "Testing a single function in isolation, apart from the rest of the system, is the smallest proof you have.",
            "A sprint is a fixed, short window where a real increment of the product gets finished, not just attempted.",
            "Process discipline isn't bureaucracy. It's what keeps a team of ten from stepping on each other's work.",
        ],
    },
    "CSE3200": {
        "title": "Design Project-II",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Design Project Two takes everything from Project One and turns it into a complete, tested system.",
            "Start by building a Minimum Viable Product the smallest working version with only the core features in.",
            "Don't confuse an MVP with a rough draft. It has to work end to end, just without every extra feature.",
            "Once new features go in, regression testing checks that they didn't break anything that worked before.",
            "A demo that only works when nothing goes wrong isn't ready. Test the paths that aren't the happy path.",
        ],
    },
    "CSE3205": {
        "title": "Computer Networks",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "networking",
        "lines": [
            "Networking is organized into layers, and the standard reference model defines exactly how many exist.",
            "TCP operates at the transport layer and guarantees reliable, ordered, connection-based data delivery.",
            "UDP sits at that same layer but skips the guarantees no acknowledgment, no ordering, no retransmission.",
            "ARP's one job is translating an IP address into the physical MAC address of the device that owns it.",
            "Know which layer a protocol lives at before you troubleshoot it. The wrong layer means the wrong fix.",
        ],
    },
    "CSE3206": {
        "title": "Computer Networks Lab",
        "lecturer": "professor_hoque",
        "emotion": "strict",
        "skill_id": "networking",
        "lines": [
            "Before debugging any network issue, confirm basic reachability first - that's what ping is actually for.",
            "Cisco Packet Tracer lets you build and configure routers and switches without needing physical hardware.",
            "A TCP connection doesn't just start sending data it opens with a specific three-step handshake first.",
            "That handshake exchanges SYN and ACK flags in a fixed order before either side trusts the connection.",
            "Capture a handshake in Wireshark once, and you'll never forget what establishing a connection means.",
        ],
    },
    "GED2248": {
        "title": "Industrial Management",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Management gets sharper with a structured way to compare a business's internal and external position.",
            "SWOT breaks that comparison into four categories: strengths, weaknesses, opportunities, and threats.",
            "Inventory carries a cost for ordering too often and a cost for storing too much EOQ finds the balance.",
            "In project scheduling, the critical path is the longest chain of dependent tasks it sets your finish date.",
            "Delay any task on the critical path and the whole project slips. Delay something else, you might be fine.",
        ],
    },

    # ── BATCH 5 ─────────────────────────────────────────────
    "CSE_ELEC1": {
        "title": "Major Elective 1",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "This elective covers ground your core courses don't cloud platforms, mobile apps, and graphics.",
            "In cloud computing, delivering a full application over the internet on subscription is one specific model.",
            "Flutter builds apps for multiple platforms from a single codebase, in a language built for exactly that.",
            "In 2D graphics, scaling an object relative to the origin comes down to multiplying by a specific matrix.",
            "Pick one of these threads and go deep. Breadth without depth won't survive a real interview question.",
        ],
    },
    "CSE3301": {
        "title": "Cyber Security",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Security starts with the weakest link, and in most breaches, that link is a person, not a system.",
            "Phishing tricks someone into handing over credentials directly no exploit needed if they just give it away.",
            "Asymmetric cryptography splits the key in two: one half encrypts, the other half alone can decrypt.",
            "SQL injection happens when user input gets treated as part of a query instead of just data inside one.",
            "Every attack in this course exploits a place where trust wasn't verified. Start looking for those places.",
        ],
    },
    "MINOR1": {
        "title": "Optional/Minor 1",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "This minor pulls together the business side you'll actually run into once you're working in tech.",
            "ERP systems tie an organization's core processes - finance, inventory, HR into one connected platform.",
            "In digital marketing, click-through rate measures how many people who saw an ad actually clicked it.",
            "Maslow's hierarchy argues lower needs like safety must be met before higher ones can motivate anyone.",
            "Business concepts feel soft compared to code, but they decide whether the code you write ever ships.",
        ],
    },
    "CSE4098A": {
        "title": "Capstone Project 1",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Capstone One isn't about building yet - it's about proving the problem you've picked is worth solving.",
            "You start by identifying the problem domain and reviewing what's already been written about it.",
            "A proposal document has to lay out your scope, your objectives, and roughly how the system gets built.",
            "A feasibility study catches a bad idea early - checking it's actually buildable before you commit months.",
            "Weak capstones fail in month one, not month four. Get the proposal right and the rest gets easier.",
        ],
    },
    "CSE_ELEC2": {
        "title": "Major Elective 2",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "ai_tools",
        "lines": [
            "This elective sits across data science and image processing two fields that lean on each other.",
            "Big Data is usually described by three properties, all starting with the same letter, worth knowing by name.",
            "Blurring an image to cut noise is usually done with a smoothing filter based on bell-curve weighting.",
            "Inside a convolutional network, a pooling layer shrinks the feature map instead of growing it, on purpose.",
            "These fields move fast. What counts as best practice this year will already be evolving by graduation.",
        ],
    },
    "CSE_ELEC2_LAB": {
        "title": "Major Elective 2 Lab",
        "lecturer": "professor_rahman",
        "emotion": "approving",
        "skill_id": "ai_tools",
        "lines": [
            "This lab sits across data science and image processing two fields that lean on each other constantly.",
            "Big Data is usually described by three properties, all starting with the same letter, worth knowing by name.",
            "Blurring an image to cut noise is usually done with a smoothing filter based on bell-curve weighting.",
            "Inside a convolutional network, a pooling layer shrinks the feature map instead of growing it, on purpose.",
            "You're applying theory with your own hands now that's where these ideas actually start to stick.",
        ],
    },
    "CSE_ELEC3": {
        "title": "Major Elective 3",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "This elective ranges across human-computer interaction, distributed systems, and how compilers work.",
            "In HCI, interface and experience are treated as two related but genuinely distinct things to design.",
            "In distributed systems, you can't have perfect consistency, availability, and partition tolerance at once.",
            "A compiler's parser doesn't just check syntax it builds a tree structure representing the program's grammar.",
            "Whichever thread you follow, the same lesson repeats: real systems always trade one property for another.",
        ],
    },
    "MINOR2": {
        "title": "Optional/Minor 2",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "This minor gives you the vocabulary to read a balance sheet and a market forecast, not just a codebase.",
            "The fundamental accounting equation ties what a business owns to what it owes and what owners hold.",
            "Price elasticity measures how sharply the quantity people buy reacts when the price itself changes.",
            "Time-series forecasting looks at data ordered by when it happened, not just what the values are.",
            "Numbers in business courses aren't abstract - every one of them is a decision someone had to defend.",
        ],
    },
    "CSE4098B": {
        "title": "Capstone Project 2",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Capstone Two moves past planning this is where the actual prototype gets built and defended.",
            "If your system touches a database, map the tables and their relationships before you write a query.",
            "That relationship map is a standard diagram, and skipping it usually shows up as schema chaos later.",
            "Integration testing proves your separately built modules actually work correctly once combined.",
            "A module that passes alone and fails when connected means the interface between them was never tested.",
        ],
    },
    "CSE_ELEC4": {
        "title": "Major Elective 4",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "This elective spans natural language processing, IoT, and blockchain three very different worlds.",
            "Before any NLP model reads text, the text gets broken into smaller units that step has its own name.",
            "IoT devices are often battery-constrained, so they lean on a lightweight messaging protocol built for that.",
            "Blockchain networks need every node to agree on one shared state that agreement process has a category.",
            "Different fields, same root problem: how do many independent parts agree on one consistent picture.",
        ],
    },
    "MINOR3": {
        "title": "Optional/Minor 3",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "This minor covers how projects manage risk and how customers actually behave once they buy something.",
            "Risk mitigation isn't about eliminating every risk - it's about reducing likelihood or impact deliberately.",
            "Cognitive dissonance shows up as discomfort when someone holds two beliefs that don't sit well together.",
            "In operations, lean thinking means cutting waste and non-value-adding steps, not just cutting headcount.",
            "These frameworks aren't just business jargon - you'll recognize them the moment you manage a real team.",
        ],
    },
    "CSE4098C": {
        "title": "Capstone Project 3",
        "lecturer": "professor_hoque",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "Capstone Three is the finish line: a working system, a full report, and a defense in front of a panel.",
            "Before that defense, acceptance testing confirms the system actually meets the original requirements.",
            "That's a different check than confirming individual functions work it validates the whole system's promise.",
            "Anyone should be able to rebuild your project from your documentation, environment notes, and dataset.",
            "A capstone that only works on your laptop, in a way only you understand, isn't actually finished.",
        ],
    },
    "CSE4099": {
        "title": "Internship / Thesis",
        "lecturer": "professor_rahman",
        "emotion": "neutral",
        "skill_id": "general",
        "lines": [
            "This track exists to put you in front of real problems, outside a classroom, with real consequences.",
            "An internship measures itself by the industry workflow you absorb, not by how many features you shipped.",
            "A thesis needs a section that critically evaluates existing research, not just lists papers you found.",
            "Every source you use has to be cited properly, and every result you report has to be reported honestly.",
            "What you produce here will outlast this semester. Treat it like something with your name on it, because it is.",
        ],
    },
}

DEFAULT_LECTURE: dict = {
    "title": "Lecture",
    "lecturer": "professor_rahman",
    "emotion": "neutral",
    "skill_id": "general",
    "lines": [
        "The lecturer works through the material at their own pace.",
        "You take what notes you can.",
    ],
}


def get_lecture(course_code: str) -> dict:
    """Return the script for a course code, or DEFAULT_LECTURE.
    Never raises, never returns None."""
    return LECTURE_SCRIPTS.get((course_code or "").strip().upper(), DEFAULT_LECTURE)