"""Which NPC offers which quest, in which semester — one per term."""
from __future__ import annotations

SEMESTER_QUEST_OFFERS: dict[int, dict] = {
    1: {"npc": "warm_classmate_purnno", "quest_id": "SQ_GIT_GITHUB",
        "offer_lines": ["The first thing here is learning Git & GitHub. Wanna tackle this together?",
                         
                         ],
        "decline_lines": ["No worries. I'll be around if you ever want to look into it."],
        "accept_lines": ["Nice! Check your PC back in your room, I'll drop the basics on there for you."]},
    2: {"npc": "professor_rahman", "quest_id": "SQ_OOP",
        "offer_lines": ["I've noticed a lot of students struggle with Object-Oriented Programming this term.",
                         "It's one of those things that clicks once you sit with it, not just read about it.",
                         "Would you like a few exercises to work through?"],
        "decline_lines": ["That's alright. The material isn't going anywhere — come find me if you change your mind."],
        "accept_lines": ["Good. I'll have it prepared for you shortly."]},
    3: {"npc": "overachiever_classmate_rafi", "quest_id": "SQ_DSA",
        "offer_lines": ["I've been grinding through Data Structures problems all week.",
                         "Genuinely feels like the stuff that actually matters once exams roll around.",
                         "You in?"],
        "decline_lines": ["Suit yourself. The problems will still be there whenever you're ready."],
        "accept_lines": ["Good call. I'll upload the set to your PC tonight."]},
    4: {"npc": "career_advisor_roya", "quest_id": "SQ_WEB_APP_DEV",
        "offer_lines": ["So, recruiters really do care about seeing an actual project, not just a transcript.",
                         "I put together a simple web app guide that could work well for your portfolio.",
                         "Want the details?"],
        "decline_lines": ["No pressure — the guide will still be there whenever you're ready to start."],
        "accept_lines": ["Perfect! Let me get everything together for you."]},
    5: {"npc": "professor_hoque", "quest_id": "SQ_AI_TOOLS",
        "offer_lines": ["These new tools everyone's using — they can sharpen your thinking, if used properly.",
                         "I don't often bother extending this. I am offering it once.",
                         "Well?"],
        "decline_lines": ["Very well. I will not offer it twice."],
        "accept_lines": ["Good. The material will be waiting on your terminal. See that you make use of it."]},
    6: {"npc": "struggling_friend_zayan", "quest_id": "SQ_LINUX_CLI",
        "offer_lines": ["Okay, weird flex, but I've gotten actually good at the terminal lately.",
                         "Like, suspiciously good for someone who used to double-click everything.",
                         "Want me to show you some stuff?"],
        "decline_lines": ["Fair enough. It's not going anywhere."],
        "accept_lines": ["Sweet, say less. Give me a sec to sort it out."]},
    7: {"npc": "late_bloomer_kabir", "quest_id": "SQ_DEBUGGING_TESTING",
        "offer_lines": ["Spent way too many nights learning how to actually debug instead of just staring at the screen.",
                         "Figured I'd save you some of that pain.",
                         "Want the notes?"],
        "decline_lines": ["Fine. It'll be there if you change your mind."],
        "accept_lines": ["Alright. I'll drop the notes on your PC."]},
    8: {"npc": "warm_classmate_purnno", "quest_id": "SQ_TECH_COMMUNICATION",
        "offer_lines": ["Funny enough, I've actually gotten decent at explaining complicated stuff simply.",
                         "All that tutoring finally paying off, I guess.",
                         "Want some pointers on documentation and writing things clearly?"],
        "decline_lines": ["No worries at all — just let me know if that changes."],
        "accept_lines": ["Great, I was hoping you'd say that. Let me put something together."]},
    9: {"npc": "professor_rahman", "quest_id": "SQ_DATABASES_SQL",
        "offer_lines": ["Databases come up far more often than most students expect, especially later on.",
                         "Worth taking a proper look, I think.",
                         "Interested?"],
        "decline_lines": ["Understood. Come back if you reconsider."],
        "accept_lines": ["Good. I'll send the material over to your computer."]},
    10: {"npc": "career_advisor_roya", "quest_id": "SQ_NETWORKING",
         "offer_lines": ["A lot of people forget networking fundamentals matter for interviews too, not just the coding round.",
                          "I put together a quick rundown.",
                          "Want to go over it?"],
         "decline_lines": ["That's alright — my door stays open."],
         "accept_lines": ["Awesome, give me a moment to pull it together."]},
    11: {"npc": "professor_hoque", "quest_id": "SQ_DOCKER",
         "offer_lines": ["Containers are not optional anymore, not in this field.",
                          "Learn it properly, once — I will not repeat myself.",
                          "Well?"],
         "decline_lines": ["Noted. Do not say I did not offer."],
         "accept_lines": ["Good. It will be waiting on your PC. Do not make me regret this."]},
    12: {"npc": "late_bloomer_kabir", "quest_id": "SQ_PROGRAMMING_LANGUAGE",
         "offer_lines": ["Still worth sharpening the fundamentals, even this late.",
                          "One last thing before you go, if you're up for it.",
                          "Want it?"],
         "decline_lines": ["Alright. Good luck either way."],
         "accept_lines": ["Fair enough. Give me a bit and I'll sort it out."]},
}